

remote_theme: #tedivm/jekyll-theme-portfolio

title: Projects
author: Talip Ucar
email: ucabtuc@gmail.com
description: Ongoing, and completed projects within various research themes in Machine Learning.


# Header Links - all optional. If set these create header links.
github_username: talipucar

# Analytics
google_analytics: 

gems: jekyll-seo-tag
