
remote_theme: tedivm/jekyll-theme-portfolio@3.5.0


title: Projects
author: Talip Ucar
email: ucabtuc@gmail.com
description: >
  This page is used to showcase ongoing, and completed projects within various research themes in Machine Learning.


# Header Links - all optional. If set these create header links.
github_username: talipucar

# Analytics
google_analytics: 


plugins:
 - jekyll-remote-theme 
